[package]
name = "sample-rt"
version = "0.1.0"
authors = ["hydry"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winrt = "0.7.0"
bindings = { path = "bindings" }
