[package]
name = "bindings"
version = "0.1.0"
authors = ["ashit"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winrt = "0.7.0"

[build-dependencies]
winrt = "0.7.0"